### ISSUE TITLE
Port to meson

### ISSUE THREAD

**Issue by bilelmoussaoui** [UberWriter/uberwriter#100]
Currently, the build system is using autotools? or it's setuptools? 
It would be great to use meson as the rest of the GNOME apps (core or third-party ones).

Let me know if you need help with that.

**Comment by somas95** [comment]
That's precisely the next thing I was going to do :)


I'll try, and if I have any difficulties I'll contact you. Thanks!

**Comment by somas95** [comment]
Hi, @bilelmoussaoui! I wanted to try this on my own but due to lack of time and knowledge...well, I failed  😅
Could you help me a little? Thanks in advance!

**Comment by BrainBlasted** [comment]
What do you need help with?

**Comment by bilelmoussaoui** [comment]
@somas95 you can assign this bug to me so I can track it later. Will send a MR soon!

**Comment by somas95** [comment]
sorry, @bilelmoussaoui, I've been really busy! Done :)
Thanks for your help! I started to dive into how meson works, but honestly I don't have the time to learn it properly in this moment. I really hope to learn reading your implementation :smile:

**Comment by somas95** [comment]
Hi, @bilelmoussaoui!
I expect to be busy til the 3 of July, but after that I'll continue the development of uberwriter and I'd like to ship everything we have so far.

I still hadn't the time to learn meson myself, could you help us with it? Thx 😄
