### ISSUE TITLE
Completely hide headerbar and statusbar while writing

### ISSUE THREAD

**Issue by bertob** [UberWriter/uberwriter#101]
Currently, the headerbar and statusbar are hidden while writing, but they just fade out, and the space below is not actually being used for content. The gradient makes it look kind of acceptable, but it's still a bit odd. 

![image](https://user-images.githubusercontent.com/1908896/50022010-26486700-ffdb-11e8-9b71-49f4e57f9359.png)

It would be nicer if instead of fading, the bars could slide out to the bottom/top respectively, and reveal content below them. Since e.g. Totem does something similar for the player controls, I assume it's at least theoretically possible.

Edit: quick mockup of what it would look like

![image](https://user-images.githubusercontent.com/1908896/50023254-e7b4ab80-ffde-11e8-9aa4-f6155357c72c.png)

**Comment by somas95** [comment]
Not only it's possible, we are doing it in the fullscreen view

**Comment by janxkoci** [comment]
Some people may like some padding around their text - maybe this could be optional?

**Comment by bertob** [comment]
> Some people may like some padding around their text 

Vertical padding? What would be the use case?

**Comment by janxkoci** [comment]
I think just from aesthetic point of view - just like you have margins on the sides, some people may want that on all sides (i.e. preserve the current state instead of the proposed "fix").

**Comment by somas95** [comment]
Obviously the content wouldn't go to the very top of the window. You can expect a similar margin between the top of the window an the text as there is between the bottom of the headerbar and the content right now

**Comment by bertob** [comment]
>  just like you have margins on the sides, some people may want that on all sides

The margins on the sides are needed to ensure a line length that's comfortable for reading/writing, but this has nothing to do with vertical padding.

I don't understand why someone would want to artificially constrain the viewport. No other application/editor does this. Content always goes to the edges of a scrollview, why wouldn't it?

FWIW, iA Writer on the Mac has the behavior I'm proposing:

![image](https://user-images.githubusercontent.com/1908896/50114049-e2a46600-0243-11e9-9392-43b91096ab0a.png)

**Comment by somas95** [comment]
@bertob on this line, what do we do with the gradient?
It doesn't follow GNOME HIG but is consistent with the look'n feel of the application
But, for some users it causes a noticeable performance hit. We're exposing the ability to hide it, solving this, but I still don't know if drop it entirely or work on it, to solve those issues

**Comment by bertob** [comment]
@somas95 without vertical margins there's no need for gradients, so I'd just remove them.

**Comment by Exalm** [comment]
> While it may be useful in gnome-shell it may not work very well in other desktop environment. For example for non full-screen window, compiz always expects a titlebar/headebar otherwise it can treat it as dock !!

Then it's already broken for most GTK3 apps, and also Firefox, Chrome and Steam, so 🤷

**Comment by somas95** [comment]
> While it may be useful in gnome-shell it may not work very well in other desktop environment. For example for non full-screen window, compiz always expects a titlebar/headebar otherwise it can treat it as dock !!

Currently the headerbar becomes invisible, but it's there, so that's not a problem anyway

**Comment by somas95** [comment]
I'm closing this as it seems to be impossible to address with the current limitations of GTK3
If a good workaround is proposed I'll implement it

**Comment by bertob** [comment]
I filed a GTK issue, hopefully we'll get a clean way to do this in GTK4: https://gitlab.gnome.org/GNOME/gtk/issues/2240

**Comment by bertob** [comment]
FWIW if we can get the behavior from this GIF I'd be ok with doing it in a hacky way in GTK3, too (unless there are other problems with this I'm not aware of).

![transient-headerbar](https://user-images.githubusercontent.com/1908896/68300071-568a6f80-009d-11ea-985c-a2f8d47eef69.gif)

Having an implementation of something in the wild, even if hacky, usually helps to get a clean solution at some point because it makes the thing more tangible :)
