### ISSUE TITLE
Can't build Flatpak in Builder

### ISSUE THREAD

**Issue by bertob** [UberWriter/uberwriter#102]
### ENVIROMENT
- Linux distribution: PureOS
- Desktop Enviroment: GNOME
- DE version: 3.30
- GTK version: 3.24
- Builder version: 3.30
- GNOME runtime version: 3.28, 3.30

### BUG
When trying to build Uberwriter from Builder, I get this error:

```
Installed /app/lib/python3.5/site-packages/uberwriter-2.1.4-py3.5.egg
Processing dependencies for uberwriter==2.1.4
Finished processing dependencies for uberwriter==2.1.4
flatpak build --share=network --nofilesystem=host --filesystem=/home/tobias/.var/app/org.gnome.Builder/cache/gnome-builder --filesystem=/home/tobias/Projects/uberwriter --filesystem=/home/tobias/Projects/uberwriter --env=PYTHON=python3 --env=IN_FLATPAK=1 --env=NOCONFIGURE=1 /home/tobias/.var/app/org.gnome.Builder/cache/gnome-builder/projects/uberwriter/flatpak/staging/x86_64-master /bin/sh -c 'glib-compile-schemas /app/usr/share/glib-2.0/schemas'
Error opening directory “/app/usr/share/glib-2.0/schemas”: No such file or directory
```

**Comment by somas95** [comment]
Are you using the json from this repo? It (probably) won't work. The one from flathub is a better way to go. In any case, I'm not happy with our current setuptools approach. I'm currently working on a port to a meson build system

One of the things that currently our setuptools script doesn't do is precisely the schemas installation. The manifest we use for flathub solves that, btw

**Comment by bertob** [comment]
Ok, I see, I'll try that then.

Perhaps you could include the flathub manifest in this repo in the meantime? It's super nice for drive-by contributions to be able to just clone a repo and click play in Builder :)

**Comment by BrainBlasted** [comment]
This was fixed by https://github.com/UberWriter/uberwriter/pull/145

**Comment by bertob** [comment]
Does that mean master should now build automatically in Builder? Because it doesn't for me at the moment.

```
Error opening directory “/app/share/glib-2.0/schemas”: No such file or directory

```

This is the error I get trying to build a fresh clone of the repo in Builder Nightly
