### ISSUE TITLE
Certain characters cause exporting to PDF to fail, and do not render in the preview

### ISSUE THREAD

**Issue by jacobranson** [UberWriter/uberwriter#107]
### ENVIROMENT
- Linux distribution: Fedora 29
- Desktop Enviroment: GNOME
- DE version: 3.30.2

### BUG
Currently using the Flatpak, attempting to use symbols like \Eta and \Omicron enclosed in $ causes the preview to render them literally, and exporting to PDF will not work. Interestingly, \eta and \omicron do work, but not their uppercase counterparts.

**Comment by wolfv** [comment]
hi! could you check if you have the same issue when using `pandoc` from the command line? Because pandoc is the software that we internally use to convert markdown to other formats.

**Comment by jacobranson** [comment]
I get an "Undefined control sequence" error when using pandoc on the same file. Interestingly, when using "omicron" with pandoc, I get this error, but in the UberWriter preview, I see the symbol render correctly. Still can't export to PDF with that symbol though.

**Comment by somas95** [comment]
The preview uses a JavaScript library to render inline LaTeX, while the pdf export uses pandoc + tex2pdf (talking from memory). That could explain the differences.
________________________________

**Comment by somas95** [comment]
Well, I've been investigating
While some letters work as you want, like \gamma and \Gamma, not all of them support that "upper case convention". This page showcases pretty well all letters:
https://www.overleaf.com/learn/latex/List_of_Greek_letters_and_math_symbols
