### ISSUE TITLE
Showing the file path in the header bar

### ISSUE THREAD

**Issue by fbruetting** [UberWriter/uberwriter#111]
Would be cool if UberWriter could show the path of the current file below the filename in the title bar – gedit does this for example, too, like you see in the screen shot. The use-case for me is, that I have several similar file names across various projects. So then it’s easier to differentiate to which project the currently visible “Notes” file belongs (I work on several projects simultaneously). What do you think?

![bildschirmfoto von 2019-02-22 18-06-20](https://user-images.githubusercontent.com/10520767/53258329-a6223a00-36cc-11e9-9b71-a4e8f3193b84.png)

**Comment by somas95** [comment]
Done 844890507c46f6cfdf8e54d69b5d16e60dc44d8f
Some improvements could be done, like

- Changing /home/[user] by ~/
- stripping the file name from the path

Those two things will be addressed when I migrate everything from os.path to pathlib methods.

**Comment by fbruetting** [comment]
Cool! Please don’t forget that on OSTree systems, the home folder is in `/var/home/<user>`, but there still is a symlink to `/home/<user>` (so both are valid home directories).

https://discussion.fedoraproject.org/t/adapting-user-home-in-etc-passwd/487/6

**Comment by somas95** [comment]
For some reason I can't install Silverblue in Gnome Boxes (seems that there's a bug in some place...)
I'll ping you when a beta version is available if you want to help test this things

**Comment by somas95** [comment]
Hi, @fbruetting!
Not the best place to write this, but it'll do the work
I finally managed to install a virtual silverblue environment! I'll test everything properly. Also, I pushed a beta version of uberwriter to flathub, so there's that.

To enable the beta channel: 
`$ flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`
Then
`$ flatpak install --user flathub-beta de.wolfvollprecht.UberWriter`

Be aware, there are still some rough edges, and the silverblue specific issues are still there. I just saw that other applications have the same problems (i.e, lollypop doesn't install the schemas)

I need to understand better how everything works, and the double sandbox doesn't make it easy 😅

I mean, lollypop installs the gschemas with a meson post-install script, and that doesn't work. We do it in the flatpak json file, and that doesn't work either... if you know anyone with experience packaging things for ostree systems, please ping him/her. I'll do my research in the meantime

**Comment by fbruetting** [comment]
@refi64, you’re one of those helpful Flatpak geniuses. Could you please give a hint? 🤓

**Comment by refi64** [comment]
👀

Off the top of my head I don't recall anything, though I might be able to look into it more tomorrow?

**Comment by somas95** [comment]
Mmmm...
On my virtual silverblue box I can't see any flatpak application with the gschemas correctly installed :thinking:

**Comment by fbruetting** [comment]
Wow, thanks very much, @refi64 !
