### ISSUE TITLE
[Question] Preview flashes momentarily and goes blank - config issue? Workaround?

### ISSUE THREAD

**Issue by HuShifang** [UberWriter/uberwriter#112]
### ENVIRONMENT
- Linux distribution: Kubuntu 18.04.02
- Desktop Enviroment: KDE Plasma 
- DE version: 5.12.7
- GTK version: 3.22.30-1ubuntu2

### QUESTION
When I attempt to preview my Markdown (e.g. the included `uberwriter_markdown.md` tutorial), the preview appears momentarily, but vanishes after an instant, leaving me with a blank screen until I revert to the raw view. I assume that this is a local configuration issue (I've had problems with GTK Flatpaks before, for reasons unknown, and simply switched to `apt` repo versions instead). Would anyone know of possible workarounds that might solve this issue?

### WHAT I DID
I installed all of the packages mentioned as prerequisites in README.md (installing `webkit2gtk-driver` at version `2.22.6-0ubuntu0.18.04.01` via `apt`) and then installed the Flatpak like so:

```
$ flatpak install flathub de.wolfvollprecht.UberWriter
Looking for matches…
Required runtime for de.wolfvollprecht.UberWriter/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.30) found in remote flathub
Do you want to install it? [Y/n]: y

de.wolfvollprecht.UberWriter permissions:
    ipc                   network       wayland      x11      file access [1]
    dbus access [2]

    [1] host, xdg-run/dconf, ~/.config/dconf:ro
    [2] ca.desrt.dconf


        ID                                          Arch     Branch  Op  Remote   Download
 1. [✓] org.gnome.Platform                          x86_64   3.30    i   flathub  301.7 MB / 419.3 MB
 2. [✓] org.gnome.Platform.Locale                   x86_64   3.30    i   flathub   17.0 kB / 223.0 MB
 3. [✓] org.freedesktop.Platform.GL.nvidia-390-48   x86_64   1.4     u   flathub   46.3 MB / 46.7 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel        x86_64   18.08   i   flathub    1.8 MB / 1.8 MB
 5. [✓] org.freedesktop.Platform.html5-codecs       x86_64   18.08   i   flathub    2.7 MB / 2.9 MB
 6. [✓] de.wolfvollprecht.UberWriter                x86_64   stable  i   flathub   34.1 MB / 34.1 MB

Changes complete.
```

**Comment by somas95** [comment]
>I installed all of the packages mentioned as prerequisites in README.md (installing webkit2gtk-driver at version 2.22.6-0ubuntu0.18.04.01 via apt) and then installed the Flatpak like so:

Just so you know, it's not necessary to install those dependencies when installing the flatpak, all of them are bundled with it. Do you mind to share a screenshot? Also, could you run uberwriter from terminal and copy&paste the output?

`flatpak run de.wolfvollprecht.UberWriter`

**Comment by HuShifang** [comment]
Good to know, thanks. 

Here's a gif of the GUI behavior: 
![uberwriter_preview_issue](https://user-images.githubusercontent.com/6540132/53749375-19117a80-3e5c-11e9-94f3-d2b3d2259208.gif)

...And here's the CLI output (from opening the app, then opening the tutorial, then switching to preview mode from the menu bar):

```
$ flatpak run de.wolfvollprecht.UberWriter 
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'Untitled'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(WebKitWebProcess:18): Gdk-ERROR **: 08:47:45.292: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 212 error_code 2 request_code 155 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Thanks again...

**Comment by somas95** [comment]
Hmmm... I've been doing some research. Could you share your specs/drivers info? Seems that this issue might happen if you don't have OpenGL...

**Comment by HuShifang** [comment]
Hey, sorry for the delay -- so it's an older Lenovo W530 with an Nvidia GK107GLM (Quadro K2000M). The system was using the X.Org X server -- Nouveau display driver when I was having this issue. I got the following CLI output when trying to see what was going on with my OpenGL version:

```bash
$  glxinfo | grep "OpenGL version" 
OpenGL version string: 4.6.0 NVIDIA 410.48
```

Honestly, I think something's gone awry with my driver situation: I had thought I was using the NVIDIA driver, and when I go to the Plasma Driver Manager GUI and attempt to change from Nouveau to one of the NVIDIA drivers I have available (two metapackages, 390 and 410, from the official repos and an old binary, 340.107, I downloaded directly from NVIDIA), nothing happens -- I'm still on Nouveau when I switch back. 

So it's probably wholly on my end. I don't know if I'll be able to do much with the drivers at the moment (things work fine for all my other apps, and I've got a busy few weeks coming up), but if I do make any progress, I'll try to post an update here...

Thanks for the follow-up!

**Comment by goncalossilva** [comment]
I have the same problem with the proprietary NVIDIA drivers (1080ti).

```
$ glxinfo  | grep "OpenGL version"
OpenGL version string: 4.6.0 NVIDIA 418.43
```

No other driver-related issues that I'm aware of.

CLI output:

```
$ flatpak run de.wolfvollprecht.UberWriter 
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'Untitled'
```

The warning only appears when entering preview mode. Hope it helps!

**Comment by somas95** [comment]
Hmm... That warning isn't related to this bug. The only advice I can give you right now is to test the beta version (is on the beta channel of uberwriter on Flathub):
`$ flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`
`$ flatpak install --user flathub-beta de.wolfvollprecht.UberWriter`

But I have the feeling that that won't fix it, but it's woth a try. Sadly I'm unable to replicate the bug, so debugging it will be hard

**Comment by somas95** [comment]
2.1.5 is out, with a new flag available to enable the webdev tools.
Just run `flatpak run de.wolfvollprecht.UberWriter -d`, enter in the preview mode, and then right click to inspect the view. Maybe it helps to find what's happening

**Comment by goncalossilva** [comment]
Preview crashes a couple o seconds after opening it unfortunately. :confused: 

```
$ flatpak run de.wolfvollprecht.UberWriter -d
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'Untitled'

(uberwriter:2): Gtk-WARNING **: 01:53:29.468: gtk_window_present_with_time() should not be called with 0, or GDK_CURRENT_TIME as a timestamp, the timestamp should instead be gathered at the time the user initiated the request for the window to be shown

(WebKitWebProcess:18): Gdk-ERROR **: 01:53:29.493: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 209 error_code 2 request_code 150 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Using `GDK_SYNCHRONIZE` as suggested has a similar result.

**Comment by somas95** [comment]
I could try that, but I'm skeptical that that will solve the issue. I've seen similar errors due to issues between webkit and graphic drivers. 
In any case a backtrace would be very helpful here, but I can't replicate the bug. If someone here has the background and time to do that, it would be awesome
