### ISSUE TITLE
Add latest version to flathub

### ISSUE THREAD

**Issue by volt4ire** [UberWriter/uberwriter#113]
The version in the Flathub repo is 2.1.3, but the project's Github releases page says the latest version is 2.1.4. Can you please update the version on Flathub? Thanks!

**Comment by somas95** [comment]
Theorically the version in Flathub should be 2.1.4
I'm trying to recompile it, it's true that the last time we had some issues (for instance, all the metadata is broken)

**Comment by somas95** [comment]
If it wasn't, now it is
