### ISSUE TITLE
Inline code in dark colour unreadable in preview when using dark mode

### ISSUE THREAD

**Issue by lightonflux** [UberWriter/uberwriter#114]
### ENVIROMENT
- Linux distribution: Debian Buster (Testing at this point)
- Desktop Enviroment: Gnome 
- DE version: 3.30.2
- GTK version: 3.24.5

- Uberwriter version: 2.1.3 (flatpak)

### BUG

Inline code has black text in preview even in dark mode. 

![bildschirmfoto von 2019-03-05 16-14-53](https://user-images.githubusercontent.com/1377943/53815430-f36e9900-3f61-11e9-96bd-26c85b9a8ce9.png)

**Comment by somas95** [comment]
fixed with 5618ff38b6023502f1538798b7cb1e218bb7ceff
