### ISSUE TITLE
Replace recently open files pop over with gedit like pop over

### ISSUE THREAD

**Issue by lightonflux** [UberWriter/uberwriter#115]
### ENVIROMENT
- Linux distribution: Debian Buster (Testing at this point)
- Desktop Enviroment: Gnome 
- DE version: 3.30.2
- GTK version: 3.24.5

- Uberwriter version: 2.1.3 (flatpak)

### BUG

At the moment it is not super easy to understand how to load a file from the recently used list. So far i only found double clicking to be working. But imho this is a bad pattern, especially because there is a "open" button next to it and it does nothing when a recently opened file is selected in the pop over. 

Inspiration: 
![bildschirmfoto](https://user-images.githubusercontent.com/1377943/53816335-ab507600-3f63-11e9-8a69-640c8c5dc26c.png)

**Comment by somas95** [comment]
Yes, it's a known issue (and I have a fix for that behaviour , see 66ccfb47c314053d7859290c1aca73331c40d51e) but I didn't have the time to test and push all the changes to flathub. Let's see if this weekend I can do that

**Comment by somas95** [comment]
2.1.5 is out with a fix for this
