### ISSUE TITLE
Crash when closing the keyboard shortcut window

### ISSUE THREAD

**Issue by lightonflux** [UberWriter/uberwriter#116]
### ENVIROMENT
- Linux distribution: Debian Buster (Testing at this point)
- Desktop Enviroment: Gnome 
- DE version: 3.30.2
- GTK version: 3.24.5

- Uberwriter version: 2.1.3 (flatpak)

### BUG

Steps to reproduce:

1. Download Flatpak with version listed above
1. Open Keyboard Shortcut Window
1. Click close on that window

#### Error messages:
```gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
kernel: traps: uberwriter[10148] general protection ip:7f7404b3f65d sp:7ffd330f1280 error:0 in libgtk-3.so.0.2404.1[7f7404b29000+35f000]
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
systemd[1824]: flatpak-de.wolfvollprecht.UberWriter-10125.scope: Succeeded.
gjs[2447]: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

![uberwriter-2019-03-05 16-46](https://user-images.githubusercontent.com/1377943/53817646-36327000-3f66-11e9-8c40-afc31c92d4ed.gif)

**Comment by rusty-snake** [comment]
Fedora 29 with GNOME + Wayland (all up2date) + lastest uberwriter flatpak don't show this behavior.

**Comment by somas95** [comment]
As @rusty-snake says, that doesn't happen with the latest version

**Comment by yodatak** [comment]
Same on: Fedora 29
UberWriter - An elegant, free distraction GTK+ markdown editor                                                  de.wolfvollprecht.UberWriter      2.1.5-beta2 stable x86_64 flathub                      system

**Comment by somas95** [comment]
I can't reproduce the crash
Any hint about the possible cause?
Is quite strange as it's a regular modal window. It doesn't even handle any logic

**Comment by thomasnaudin** [comment]
### ENVIROMENT
- Linux distribution: Fedora 30
- Desktop Enviroment: Gnome
- DE version: 3.32.2
- GTK version: 3.24.9

Same here on Fedora 30. UberWriter 2.1.5-beta2 from Flathub.

**Comment by thomasnaudin** [comment]
I noticed it seems to crash only on Xorg session.
No problem with Wayland.
