### ISSUE TITLE
Subsequent elements in a list are not properly indented to the left

### ISSUE THREAD

**Issue by fbruetting** [UberWriter/uberwriter#120]
Especially as a user of a unicode using keayboard (German Neo 2), I often itemize by the usage of more suiting characters like `•` (bullet), `–` (proper itemization dash) and `·` (centered dot), so my text also looks halfway marked up on non-Markdown text viewers.

Do you maybe like to handle these characters like `*` and `-` (hyphen!) are handled, and thus also use them for marking up itemizations?

**Comment by somas95** [comment]
Those work, no? 

![Edit mode](https://user-images.githubusercontent.com/8913975/54084527-41084e80-4332-11e9-8968-a3c646b98e94.png)
![Preview mode](https://user-images.githubusercontent.com/8913975/54084529-482f5c80-4332-11e9-8a30-e7c8e267ffa6.png)

Remember to leave an empty line before the list (that's how markdown work...)

If that's not the issue, could you drop a test file?

**Comment by fbruetting** [comment]
Well, yeah, it works – but it’s not handled the same way as “correct” itemizations. So for the correct ones, the first level is off by a left-shifted indentation, but the unicode itemizations are not. So in fact, the unicode itemizations are correct, and the regular ones are not. This irritated me first, but now I realize that the unicode itemizations actually are more correct than the default ones. :D

![Bildschirmfoto von 2019-03-10 22-38-03](https://user-images.githubusercontent.com/10520767/54091846-417e0500-4385-11e9-9d3a-4c666fcd6586.png)

**Comment by wolfv** [comment]
I think making a PR for this wouldn't be so hard. Maybe you want to give it a try @fbruetting ?

**Comment by somas95** [comment]
Some annotations first:

- for "correct" itemizations, the left-shifted indentation is a feature, not a bug. But consequent levels should have that shifting too. We do that shifting to headers and some other markup elements, so the content is always left aligned

- we should be sure that pandoc allows those symbols as indentation elements

All that said, a PR will be more than welcome :)

**Comment by fbruetting** [comment]
I’m home just about to sleep, so no chance at the moment.

And indenting by different levels is a bug to me. Look at the difference between the three levels.

**Comment by somas95** [comment]
Sorry for the delay
I'm sorry, but pandoc only allows hyphens and asterisks as valid item tokens. See the exported pdf:
![image](https://user-images.githubusercontent.com/8913975/54859218-e647fd00-4d0a-11e9-92e4-281f69d2127d.png)
I checked their documentation, and didn't find any option or flag to enable them 

Regarding the shifting, the bug is that consequent items are not shifted to the left the same amount. I'll look into that

**Comment by fbruetting** [comment]
> Regarding the shifting, the bug is that consequent items are not shifted to the left the same amount. I'll look into that

Why the shift in the first place?
Currently code parts with leading dashes (e.g. YAML) look corrupted:

![Bildschirmfoto von 2019-04-28 22-45-20](https://user-images.githubusercontent.com/10520767/56869891-55e69180-6a07-11e9-8f13-453305805ba6.png)
