### ISSUE TITLE
Emoji rendering in preview is black & white

### ISSUE THREAD

**Issue by goncalossilva** [UberWriter/uberwriter#121]
### ENVIROMENT
- Linux distribution: Fedora 29
- Desktop Enviroment: Gnome
- DE version: 3.30
- GTK version: 3.24.1-2.fc29

### BUG

Emoji rendering in preview is black & white. This:

![Screenshot-20190320022507](https://user-images.githubusercontent.com/102931/54654833-74c44080-4ab7-11e9-9b3f-9e6da7f9de82.png)

turns into this:

![Screenshot-20190320022519](https://user-images.githubusercontent.com/102931/54654846-7beb4e80-4ab7-11e9-86b2-38697f7ed206.png)

I would assume this is a misconfiguration on my system as I have experienced this before (early days of Fedora 28), but everything was sorted over time and I haven't seen any app or browser behave this way in a long time.

I doubt it's relevant, but I also experience [the flash](https://github.com/UberWriter/uberwriter/issues/112) (using a 1080ti with the proprietary drivers).

Related with the preview, a question: the font doesn't look good (eg. note all the "i"). What is being used? I don't think I see this anywhere else?

**Comment by somas95** [comment]
The font used is encoded in base64, and it shouldn't show those perks:
https://github.com/UberWriter/uberwriter/blob/886b292a10881e59195152cad0d096c09d26a0e7/data/media/github-md.css#L3

The emoji thing seems related to the issue with the font used for the preview mode. I'll take a look this afternoon

**Comment by somas95** [comment]
Ok, for some reason the non-flatpak development version I'm using doesn't show any emoji in the preview. I have the feeling that it's related to some changes the WebkitGtk team did in the last version https://webkitgtk.org/2019/03/13/webkitgtk2.24.0-released.html related with coloured emojis precisely. That was a week ago, so I'll wait to view if a bugfix release fixes that

**Comment by goncalossilva** [comment]
@somas95 Out of curiosity, why are we specifying the font instead of falling back to the system one?

**Comment by somas95** [comment]
Ligatures -yes, emoji rendering -no.
We are using a css stylesheet to mimic the one github uses to render his markdown content. But yes, the font is not super important (though I rather specify one than using the system default one). Any suggestion is welcome. Maybe we could use the regular Fira one, since we are using the Fira Code for the edit view.

Regarding emojis, now I'm pretty sure WebKitGTK is at fault here. It's as easy as launch uberwriter with the 3.30 and the 3.32 GNOME runtimes, with the prior one emojis are displayed, with the second one, no.

More and more, other apps which use the WebKitGTK module show the same issue

**Comment by goncalossilva** [comment]
Thanks, makes sense.

> Maybe we could use the regular Fira one, since we are using the Fira Code for the edit view.

This makes a lot of sense to me. :+1:

**Comment by goncalossilva** [comment]
I've looked a bit more into this, and I think there is a mistake. You mentioned:

> The font used is encoded in base64, and it shouldn't show those perks:

The font is indeed specified, but never used. It's just a declaration without usage. In fact, within the same stylesheet, `font-family` uses all point to something else (or inherit):
* https://github.com/UberWriter/uberwriter/blob/886b292a10881e59195152cad0d096c09d26a0e7/data/media/github-md.css#L12
* https://github.com/UberWriter/uberwriter/blob/886b292a10881e59195152cad0d096c09d26a0e7/data/media/github-md.css#L47
* https://github.com/UberWriter/uberwriter/blob/886b292a10881e59195152cad0d096c09d26a0e7/data/media/github-md.css#L197
* https://github.com/UberWriter/uberwriter/blob/886b292a10881e59195152cad0d096c09d26a0e7/data/media/github-md.css#L204

I'll revise this later today and send a PR.

As for the originally reported issue, the good news is that when running the code locally emojis are correctly in the preview. :thinking:

**Comment by somas95** [comment]
Thanks for the PR! I'll review and merge it in a moment

>As for the originally reported issue, the good news is that when running the code locally emojis are correctly in the preview. :thinking: 

What is the version of WebKit you're using? Maybe it's not 2.24. Run 

` >>> import gi`
 ` >>> gi.require_version('WebKit2', '4.0')`
` >>> from gi.repository import WebKit2`
` >>> print(WebKit2.MINOR_VERSION)`

It should show 24, if not you won't be able to reproduce the bug

**Comment by goncalossilva** [comment]
Ah, you're absolutely right:

```
>>> import gi
>>> gi.require_version('WebKit2', '4.0')
>>> from gi.repository import WebKit2
>>> print(WebKit2.MINOR_VERSION)
22
```

I did though notice that depending on how `font-family` was setup in the CSS, there were varying differences in terms of emoji support. I have improved this in a fork, will PR soon.

**Comment by somas95** [comment]
Regarding the emoji thing, theoretically the webkit folks have added support to colored emojis in 2.24 without needing emoji fonts etc, so I would wait until they fix the issue with them. Maybe it's not necessary to do anything else
https://www.webkitgtk.org/2019/03/13/webkitgtk2.24.0-released.html

**Comment by goncalossilva** [comment]
Makes sense, but please note that the branch that was merged does not use any emoji font. It uses the ones from the system, if present. It's a thorough list that most platforms use, with Noto added (which is the default on most distros). But no added emoji font. :smile:
