### ISSUE TITLE
GitHub-flavored markdown?

### ISSUE THREAD

**Issue by goncalossilva** [UberWriter/uberwriter#122]
### ENVIROMENT
- Linux distribution: Fedora 29
- Desktop Enviroment: Gnome
- DE version: 3.30
- GTK version: 3.24.1-2.fc29

### BUG

There are subtle differences in how markdown is handled in UberWriter, and most other places that use GitHub-flavored markdown (eg. GitHub itself, Twist, Typora, Slack, etc).

An example is how paragraphs are handled. Notice the difference:
![Screenshot-20190320023204](https://user-images.githubusercontent.com/102931/54655114-8fe38000-4ab8-11e9-82db-bddb4dcc72e1.png)
![Screenshot-20190320023214](https://user-images.githubusercontent.com/102931/54655113-8fe38000-4ab8-11e9-8b76-db9db6fe8662.png)
![Screenshot-20190320023118](https://user-images.githubusercontent.com/102931/54655116-8fe38000-4ab8-11e9-9951-080b1b404668.png)
![Screenshot-20190320023125](https://user-images.githubusercontent.com/102931/54655115-8fe38000-4ab8-11e9-8ab0-bf8bfbbaf85c.png)

I am not sure this is related with the (lack of?) support for GitHub-flavored markdown, or something else entirely. If it is the former, is there any chance we could add a toggle in the settings to have pandoc use the `gfm` input format?

**Comment by goncalossilva** [comment]
This is likely related: https://github.com/UberWriter/uberwriter/issues/17

**Comment by goncalossilva** [comment]
I can give this a try if you're interested. I was thinking of adding a dropdown to the settings to specify the input format, and include:
* Pandoc's markdown (default)
* Commonmark
* GitHub-flavored markdown

Besides the setting, I don't think other adjustments would be needed aside from using it [here](https://github.com/UberWriter/uberwriter/blob/d65008a92a2cdbd8b58b2cd341ee547533d0e439/uberwriter/UberwriterWindow.py#L852)? Or does the CSS need tweaking as well?

**Comment by somas95** [comment]
Yes, I could give it a try. In fact I implemented some things from GFM by hand, like the task list support. For GFM I don't think more adjustments were necessary, but I'm not so sure about CommonMark. Subtle syntax changes could break the inline preview -wich relies in RegEx- but I could push that to the beta channel to proper test it

**Comment by goncalossilva** [comment]
@somas95 I write tons of markdown and would love to test this and provide feedback. I can also help with development if it's productive (seems like it isn't in this case).
