### ISSUE TITLE
Add shortcut to Scratch

### ISSUE THREAD

**Issue by yodatak** [UberWriter/uberwriter#130]
### ENVIROMENT
- Linux distribution: Fedora 29
- Desktop Enviroment: Gnome

### Feature
It's cool be cool to add a shortcut to scratch text ?
like this 
Strikethrough uses two tildes. ~~Scratch this.~~

**Comment by somas95** [comment]
It exists! It's ctrl+shift+d 
I'll add an entry in the shortcut window :)
