### ISSUE TITLE
Option for disabling auto-hiding headerbar

### ISSUE THREAD

**Issue by fbruetting** [UberWriter/uberwriter#131]
I think UberWriter could get even more awesome, if the auto-hiding function of the header bar could be turned off (maybe even by default). This would lead to more consistency with respect to other GTK/Gnome windows, and would enable a quick glance on which document a UberWriter instance actually shows – especially if you use multiple instances across multiple virtual workspaces (like I do all the time).

Furthermore, it looks a bit strange if you tile two windows on a workspace and one shows its headerbar and the other one does not. So maybe it’s also a good idea to additionally restrict the auto-hiding functionality to full-screen windows only?

What do you think?

**Comment by somas95** [comment]
Regarding disabling the auto-hiding behavior: currently you can do that setting the poll-motion option to false on dconf:

`/de/wolfvollprecht/UberWriter/poll-motion`

That doesn't change the auto-hiding on fullscreen, so you'd achieve the behavior you want

In my opinion the auto-hiding on window-mode is a useful feature. Maybe we could put an option to disable it on the settings dialog though

**Comment by fbruetting** [comment]
Hm, I don’t see this setting, I just see the three settings of the settings menu and `open-file-path`. When I go into the Flatpak by `flatpak run --command=sh de.wolfvollprecht.UberWrite`, even `gsettings get de.wolfvollprecht.UberWriter.dark-mode` doesn’t show me anything.

GUI option would be cool!

**Comment by somas95** [comment]
Hmm, seems that when a schema is installed it's no longer updated or something. Maybe your installation isn't up to date. Anyway, right now I'm porting everything to the meson build system, so I hope this kind of issues will be mitigated.

In the meantime, you can install the correct schema moving https://github.com/UberWriter/uberwriter/blob/master/data/de.wolfvollprecht.UberWriter.gschema.xml to /usr/share/glib-2.0/ and then run
`sudo glib-compile-schemas /usr/share/glib-2.0/schemas`

**Comment by fbruetting** [comment]
I run Silverblue with fixed OSTree image and layers. Therefore I am not able to alter `/usr/`.

**Comment by somas95** [comment]
that happens when an app, in this case uberwriter, writes a key:value pair not defined by a schema. In other words, that you don't have the de.wolfvollprecht.UberWriter.gschema.xml file installed. Uberwriter still can write arbitrary settings in his dconf "space", but it's less than ideal. Just out of curiosity, can you paste the content of your /usr/share/glib-2.0/schemas/de.wolfvollprecht.UberWriter.gschema.xml, if exists?

**Comment by fbruetting** [comment]
It’s not there, but I found it in the flatpak sandbox under `/app/share/glib-2.0/schemas/de.wolfvollprecht.UberWriter.gschema.xml`:

```xml
<?xml version="1.0" encoding="utf-8"?>

<schemalist>

  <schema path="/de/wolfvollprecht/UberWriter/" id="de.wolfvollprecht.UberWriter">

    <key name='dark-mode' type='b'>
      <default>false</default>
      <summary>Dark mode</summary>
      <description>
        If enabled, the window will be dark themed
        If disabled, the window will be light themed
        asked to install them manually.
      </description>
    </key>
    <key name='spellcheck' type='b'>
      <default>true</default>
      <summary>Spellcheck</summary>
      <description>
        Enable/disable spellchecking in the application.
      </description>
    </key>
    <key name='gradient-overlay' type='b'>
      <default>false</default>
      <summary>Show gradient overlay</summary>
      <description>
        Show a gradient overlay over the text at the top anf bottom of the window.
        It can cause performance problems to some users
      </description>
    </key>
    <key name='poll-motion' type='b'>
      <default>true</default>
      <summary>Allow Uberwriter to poll cursor motion</summary>
      <description>
        Used for hidding the headerbar after 3 seconds if the cursor is not moving.
      </description>
    </key>
    <key name='open-file-path' type='s'>
      <default>"/tmp"</default>
      <summary>Open file base path</summary>
      <description>
        Open file paths of the current session
      </description>
    </key>

  </schema>

</schemalist>
```

**Comment by somas95** [comment]
I'll set up a ostree vm to properly test this. It's easy that compiling the schemas on that path will do the trick, but I'll take a close look. As I said I'm porting the build system to meson, so I'll take care of this details 

Thanks for reporting that!

**Comment by fbruetting** [comment]
Would you like to re-open for not forgetting about that? :)

**Comment by somas95** [comment]
I keep this in mind, as is part of the work I'm currently doing (the meson port), but thanks :)

**Comment by somas95** [comment]
Well, seems that installing gschemas in ostree systems is far from trivial, and I haven't seen any program that does it, at least flatpak ones

So, one workaround is this:

` dconf write /de/wolfvollprecht/UberWriter/poll-motion false`

If you don't delete that key, you should be fine, even after reboots etc. Except across reinstalls, then I'm not sure what would happen

**Comment by fbruetting** [comment]
Now this dconf issue seems to be resolved:

https://www.phoronix.com/scan.php?page=news_item&px=Flatpak-1.4-Released
https://github.com/flatpak/flatpak/pull/2678

Wanna reopen for not forgetting about that? ;)

**Comment by somas95** [comment]
Now we use a keyfile GSettings backend. You can edit options directly on
` ~/.var/app/de.wolfvollprecht.UberWriter/config/glib-2.0/settings/keyfile`
write at the end of that file 
`poll-motion=false` and you'll be good to go. Of course, that path will change if uberwriter is installed system-wide, or maybe on silverblue systems
