### ISSUE TITLE
Opening multiple windows not possible

### ISSUE THREAD

**Issue by fbruetting** [UberWriter/uberwriter#136]
### ENVIROMENT
- Linux distribution: Fedora 28
- Desktop Enviroment: GNOME
- DE version: 3.28.2
- GTK version: 3.22.30

### BUG
I cannot open multiple windows at all. The dock context menu option “New Window” doesn’t work. Double-clicking on other Markdown files in Nautilus (with UberWriter being the default application) also doesn’t work with an already existing instance, because instead of a new window being generated, the old UberWriter window somehow gets moved to foreground and nothing happens.

I will verify that behavior on my Fedora Silverblue 30 machine tonight.

**Comment by somas95** [comment]
Right now uberwriter is not prepared to handle different files at the same time, that's why we don't allow multiple instances. Support for multiple windows is planned though

**Comment by somas95** [comment]
duplicated of #72
