### ISSUE TITLE
Non-symbolic icon in Shell top bar

### ISSUE THREAD

**Issue by bertob** [UberWriter/uberwriter#137]
### ENVIROMENT
- Linux distribution: PureOS
- Desktop Enviroment: GNOME
- DE version: GNOME 3.30
- GTK version: 3.24.5
- App version: 2.1.5 (Flathub)

### BUG

In the GNOME Shell top bar I'm getting the full-color icon rather than the symbolic:

![image](https://user-images.githubusercontent.com/1908896/55619472-078ffb00-5799-11e9-9d77-69b6b7b3059e.png)

**Comment by somas95** [comment]
I'm not sure how to set which icon is used in the top bar
I've searched the docs without luck...

**Comment by somas95** [comment]
Well, 9ae1eaedda069ec50e909be9abdf10cecf204838 should fix it
