### ISSUE TITLE
Add method to increase and decrease font size

### ISSUE THREAD

**Issue by diazbastian** [UberWriter/uberwriter#141]
### ENVIRONMENT
- Linux distribution: Fedora 30 beta (64 bit)
- Desktop Enviroment: GNOME
- DE version: 3.32.1
- GTK version: 3.24.7

### Improvement

Currently it is not possible to handle the size of the font in Ubewriter, in addition, this is modified depending on the size of the window. I think that this approach is not the most appropriate for the following reasons:

* There is no consistency in the content depending on the size of the window (including full screen)
* The default value of the system font size is not respected (Including universal access settings)

I think that using the default font size granted by the system plus the possibility of increasing and decreasing the size of the font is the best option being the most common.

**Comment by somas95** [comment]
I'm going to share my thoughts on this:

While I think it's not a bad idea to be able to change font size, I wouldn't approach it as you suggest. The idea here is to have a constant (and well thought) max. number of characters in each line (72), as is a well known line length value to help readability. In fact, font size changes when you change the window size to maintain that line length, and if the document loses consistency when doing so, it's a bug that should be addressed. 

That said, allowing users to change the line length (maybe between 50 and 80 chars/line) is not off the book

Also, if there is a way to detect whether universal access "big text" option is enabled, I'll change the default value to a more appropriate one.

Thanks for the feedback!

**Comment by diazbastian** [comment]
> The idea here is to have a constant (and well thought) max. number of characters in each line (72), as is a well known line length value to help readability.

I see, now I understand.

> In fact, font size changes when you change the window size to maintain that line length, and if the document loses consistency when doing so, it's a bug that should be addressed.

Interestingly I set out to try this using the UW tutorial and didn't find the changes I saw with more extensive and complex documents. For example when using the full screen the size of the font grew a lot or the window didn't react to gsnap (drag the window to an edge and occupy the middle of the screen in gnome-shell). It is something that I will try to replicate and write a report if it is a bug.

Anyway, I think that in some cases increasing the size of the font is essential (eg using UberWriter full screen on a high resolution monitor at night).

> Also, if there is a way to detect whether universal access "big text" option is enabled, I'll change the default value to a more appropriate one.

Thank you
