### ISSUE TITLE
Pdf Exports Do Not Preserve Links

### ISSUE THREAD

**Issue by BrainBlasted** [UberWriter/uberwriter#153]
### ENVIROMENT
- Linux distribution: Arch Linux (flatpak from flathub)
- Desktop Enviroment: GNOME
- DE version: 3.32
- GTK version: 3.24.x

### BUG

When exporting as a PDF, all the links within the PDF are dropped.

**Comment by somas95** [comment]
Sorry for the delay
Could you provide a test file? If we are talking about links to web addresses I can't reproduce it
