### ISSUE TITLE
Metadata blocks incorrectly formatted

### ISSUE THREAD

**Issue by alerque** [UberWriter/uberwriter#154]
(uberwriter-git-2.2.0.beta1.4.r0.g181af44 on Archlinux w/ GTK 3.24.8)

It looks like Pandoc's `yaml_metadata_block` syntax is not recognized:

```markdown
# Giriş

---
author: Greg Strawbridge
---

Benim teolojik köşkümde birçok oda mevcut.
```

...results in rendering like this:

![image](https://user-images.githubusercontent.com/173595/56860345-6a427400-699e-11e9-9fe9-c23082657cd2.png)

**Comment by goncalossilva** [comment]
Thanks for the report! I'll fix this. :+1:

**Comment by fromrileywithlove** [comment]
This has regressed as of commit a9650d86bfc6022393db566ee306e326101f35b5. Or at least, this seems incorrect.

![image](https://user-images.githubusercontent.com/59788665/72861630-79323900-3d1a-11ea-934a-3475afbd2bcc.png)
