### ISSUE TITLE
Default tab indentation of 4 spaces

### ISSUE THREAD

**Issue by fbruetting** [UberWriter/uberwriter#156]
As really nearly everything in the world (with just a few exceptions) uses a tab width of four spaces, it would be cool if UberWriter could do this, too! This especially helps raw-reading Markdown files in normal text editors, because the differences to UberWriters marked-up display then would be much less.

Also, four spaces is a good fit in between the way more seldomly used tab widths of 8 (mainly Linux kernel and some other C stuff) and 2 (which are somewhat needed in HTML, because web devs sadly stick to 90s `div` hell instead of applying nowaday’s CSS grid).

**Comment by somas95** [comment]
I have no problem with this (personally speaking). What do you think, @wolfv , @goncalossilva?

**Comment by goncalossilva** [comment]
This is already done with the latest markup iteration, [ref](https://github.com/UberWriter/uberwriter/blob/master/uberwriter/text_view_markup_handler.py#L300) :smile: 

It was needed to support indented lists properly.

**Comment by somas95** [comment]
Perfect! You're amazing, @goncalossilva
