### ISSUE TITLE
feature request: add commonmark support!

### ISSUE THREAD

**Issue by jjmhtp** [UberWriter/uberwriter#17]
plz! :-)

**Comment by wolfv** [comment]
pandoc supports commonmark ... do you know if we need to pass some special flag for common mark or is there a certain file ending?

**Comment by wolfv** [comment]
:)

**Comment by RoyiAvital** [comment]
I would add [CriticMarkup](http://criticmarkup.com/) as well.

**Comment by bluebirch** [comment]
`pandoc -f commonmark`
