### ISSUE TITLE
[BUG] Translation files in wrong place

### ISSUE THREAD

**Issue by tim77** [UberWriter/uberwriter#173]
**Describe the bug**
Uberwriter put translation in `/usr/lib/python3.7/site-packages/po` but this is incorrect place. Also it includes the `po` files and build scripts, which shouldn't be distributed along `mo` files.

**Expected behavior**
Translation files in correct and standard location
`/usr/share/locale`

**Environment(please complete the following information):**
- Linux distribution: Fedora 30
- Desktop Enviroment: GNOME
- DE version: 3.32
- GTK version: 3.24

**Comment by wolfv** [comment]
Thanks for the bug report! Are you interested in making a PR for this?

**Comment by tim77** [comment]
I can not promise when, but yep. 😊 I also noticed that there is a plan for port it to meson. Probably we need to sync this.

**Comment by somas95** [comment]
Hi, @tim77! Yes, we're doing a port to the meson buildsystem as we speak, so this issue will be automatically solved. Thanks!
