### ISSUE TITLE
[Feature Request] Port to OS X?

### ISSUE THREAD

**Issue by akierig** [UberWriter/uberwriter#175]
It'd be really great if it was possible to get this via MacPorts (or Brew) on OS X. Switching back and forth means using different editors with different behaviors and I like Uberwriter a lot more than the OS X editors I've tried, e.g. [MacDown](https://github.com/MacDownApp/macdown).

I tried building it from source but didn't have any luck. Other suggestions welcome.

**Comment by somas95** [comment]
Duplicate of #48 

I'm going to add some resources there, but I still lack the knowledge and/or the hardware needed to do that port. In any case this is something I'd like to do at some point, and any help is well received
