### ISSUE TITLE
[Feature Request] Export to PDF in A4 paper size

### ISSUE THREAD

**Issue by lavendthomas** [UberWriter/uberwriter#180]
Hi,

Most of the world doesn't use US Letter paper. So if we write a file we want to print, it would be nice to easily change the paper format of the exported PDF file. My current workflow would be to export to LaTeX then modify the LaTeX file and then export to PDF.

The best place I found for these settings would be the following:

- In the PDF tab, it could be below the file picker, like LibreOffice Writer is doing for the file format, or gedit in the save menu. 
- In the Advanced tab, it could fit in the general options or better add a PDF Options sections like the HTML sections.

If you search for "a4" on [Pandoc's Maual](https://pandoc.org/MANUAL.html), you can choose the paper format with an argument: (also see [Pandoc issue 600](https://github.com/jgm/pandoc/issues/600))

```
-V papersize:"a4paper"
```

Also, is there a way to enable PDF export when building with GNOME Builder ? It asks me to install de.wolfvollprecht.UberWriter.Plugin.TexLive from Flathub, but I already have it installed. I  originally wanted to try to implement these changes myself to learn and then pull request.

Also, I requested access to the French translation in POEdit ;-)

**Comment by wolfv** [comment]
Hi @lavendthomas thanks for opening this issue. Totally makes sense. A PR would be very much appreciated :)

Maybe you could overwrite the check for testing wether texlive (or the flatpak plugin) exists (just to get the dev environment set up?)

E.g. just change this line to `= True` for the moment:

https://github.com/UberWriter/uberwriter/blob/6a6b5f4c6967a8a62a08cebc32d1564ea330559a/uberwriter/export_dialog.py#L174

**Comment by somas95** [comment]
Years using and developing uberwriter and I just realized that I was exporting to US Letter format all the time. I'll push a quick fix soon, thanks to pointing it out!

> Maybe you could overwrite the check for testing wether texlive (or the flatpak plugin) exists (just to get the dev environment set up?)

That won't work I fear. I'll investigate how to solve it

>Also, I requested access to the French translation in POEdit ;-)

I saw it! Access granted :)

**Comment by somas95** [comment]
Solved by 17c20199f510000474bd4e9993f0ee37440a3a01
Added a card too https://github.com/UberWriter/uberwriter/projects/3#card-29909356, I'll make "papersize" an advanced export option

**Comment by lavendthomas** [comment]
I sent a pull request (#181) to add the option. (Sorry to re-open the issue)
