### ISSUE TITLE
[Feature Request] Automatic substitution

### ISSUE THREAD

**Issue by lavendthomas** [UberWriter/uberwriter#182]
I personally use UberWriter to take notes, so being efficient is important.

Having UberWriter automatically substitute characters for others would be a useful. For example, ==> could be replaced by ⇒ or it could be used to expand abbreviations. 

The substitution could be word-based (like in office suites), when a word delimited by spaces or new lines matches a list, it is substituted.

For where to add it in the settings, the best place I could think of is to add tabs in the settings dialog (like in Gedit or other GNOME apps). One section for the general settings and another for the spell-checker, auto-substitution and auto-complete braces (#89).

**Comment by somas95** [comment]
The quick answer is that I don't plan to support automatic substitution nor other "advanced" word processing features (I think they fall out of scope), but  depending on the implementation for #89 maybe we could expose somehow a file so the user can add their own substitutions. I mean, if I'm gonna write a substitution engine to change
```
{ -> {|}
[ -> [|]
( -> (|)
```
and so on, I don't see any reason to not expose it, but being that as I said it fails out of scope, and can introduce some issues (parsing ones, for example) I won't officially support it (maybe a tiny tiny link to the file in settings, perhaps?)

For the moment I'll close this issue as "won't fix" and add a note to the brainstorming column. I'll revisit this when working on #89 

Thanks for the suggestion!
