### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by lucamondini** [UberWriter/uberwriter#190]
Hi, my system language is English but I use to write in Italian very often. However I can't select it among the available spell-check languages. How can I add it?
Hunspell-it is already installed and I also reinstalled Gnome Platform Locales SDK as you suggested in a FAQ since UberWriter is installed as a flatpak package.
Thank you!

**Comment by lucamondini** [comment]
Ok, I got it: I reinstalled the Gnome Platform Locales SDK for 3.34, but in my system (Fedora 31) UberWriter uses 3.32. So, I just reinstalled for 3.32 as well and now it works.

I found also a 'not so clean' solution: all the dictionaries are usually installed into /usr/share/myspell.
Copying them into [runtime]/files/share/myspell does the job.

**Comment by wolfv** [comment]
good to hear! thanks for updating the issue.
