### ISSUE TITLE
Links to images followed in preview mode

### ISSUE THREAD

**Issue by lavendthomas** [UberWriter/uberwriter#193]
When you create a link to an image, it becomes click-able in preview mode. When clicking on it, two things happen:

- The image is opened in the default browser.
- The WebView switches to only showing the image. The only way to go back to the preview of the whole text is the close and reopen the preview.

**Steps to reproduce the behavior:**

1. Create a file containing `[link](/path/to/img.png)`.
2. Switch to preview mode.
3. Click on the link.

**Expected results:**

The app should either:

- Only open the file on the default browser
- Not open the image on the default browser, but enlarge the picture with a way of going back (e.g. add a back button to the headerbar).

**Environment:**
- Linux distribution: Fedora 31
- Desktop Enviroment: GNOME
- DE version: 3.34.3
- GTK version: 3.24.13

**Comment by somas95** [comment]
Ok, we don't want to turn uberwriter into a web browser. So not following links would be the best approach IMO

How to do that, I'm not sure. I've been suggested that the ephemeral property could do the trick, but I'm not sure

**Comment by goncalossilva** [comment]
The image opening in the default browser is expected, but the webview switching to it isn't. There's [handling for this](https://github.com/UberWriter/uberwriter/blob/master/uberwriter/preview_web_view.py#L89-L94). :thinking:

**Comment by lavendthomas** [comment]
Thank you @goncalossilva, you saved me so much time researching how WebKitGtk works !
