### ISSUE TITLE
[BUG] Can't open Markdown files using the file choosers

### ISSUE THREAD

**Issue by sternenseemann** [UberWriter/uberwriter#196]
**Describe the bug**

When I open the file chooser neither „Plain Text“ nor „Markdown“ option shows any `.md` files.

I suspect this is caused by my GTK not having the MIME types set up properly. UberWriter should have an all files options for opening files to account for rare cases where you'd have odd file names and maybe even complement the MIME type based file chooser with a file extension based one?

**Expected behavior**
UberWriter should show `.md` files

**Environment(please complete the following information):**
- Linux distribution: NixOS
- Desktop Enviroment: GNOME
- DE version: 3.34.2
- GTK version: 3.24.12

**Comment by somas95** [comment]
I need some more information

Are you using the NixOS package, or the flathub one? (I guess we're talking about the former)
About what version of Uberwriter are we talking about?

In any case, I think it's a good suggestion to have the "all files" option, so I'll add that for the next version. 

In the meantime let's see what's happening to the NixOS package

**Comment by sternenseemann** [comment]
The NixOS package uses an „unstable“ version from master in order to use the new `meson` build system which is much better. Currently it is on revision 7606a55389f8516d9fed7927fa50ff8822ee9e38.

My suspicion is currently that, since there is no global mime-type database on nixos e. g. `/usr/share/applications` etc. this might cause some trouble. I'll investigate which package / environment variables I have to add. I'm sadly not exactly sure where GTK looks for mime type info.

**Comment by sternenseemann** [comment]
Enabling XDG mime info globally using [this option](https://nixos.org/nixos/options.html#xdg.mime) resolves the issue on NixOS, so its no bug of UberWriter sorry. I'll see wether I can improve the package, so it works properly regardless of system configuration.

**Comment by somas95** [comment]
Also, Uberwriter has plaintext mimetypes set on the filechooser. See https://github.com/UberWriter/uberwriter/blob/7606a55389f8516d9fed7927fa50ff8822ee9e38/uberwriter/main_window.py#L325

**Comment by sternenseemann** [comment]
Yeah, I also confirmed that works with the change in the package, but not with the current version.
