### ISSUE TITLE
[Feature Request] Add "all files" to the mimetype list

### ISSUE THREAD

**Issue by somas95** [UberWriter/uberwriter#197]
Related with #196

**Comment by somas95** [comment]
It's already there

**Comment by sternenseemann** [comment]
No? At least not in the open file dialog. Compiled from master: 

![Screenshot from 2020-02-06 21-37-20](https://user-images.githubusercontent.com/3154475/73976644-071c3f80-4929-11ea-83f8-98211e13897c.png)
