### ISSUE TITLE
Hemingway mode

### ISSUE THREAD

**Issue by suhr** [UberWriter/uberwriter#40]
Like in [ghostwriter](https://wereturtle.github.io/ghostwriter/).

**Comment by lightonflux** [comment]
For people as confused as me:

> Hemingway Mode
> 
> Clicking on the "Hemingway" button in the lower right corner of the editor will disable your backspace and delete keys, creating a typewriter experience. This feature is especially useful if you want to avoid editing and force yourself to write.
