### ISSUE TITLE
L10n

### ISSUE THREAD

**Issue by somas95** [UberWriter/uberwriter#49]
Currently UberWriter lacks a lot of localization
We could consider using [Poeditor](https://poeditor.com/kb/open-source-localization), which has a free and unlimited plan for OSS projects, to ease the task to possible contributors
It also has Github integration, so it would be pretty easy to manage

**Comment by wolfv** [comment]
hey, yes, let's do that. just FYI there was a translation project on launchpad as well. https://translations.launchpad.net/uberwriter
We should probably synchronize the translations from there, and then move over to another service. 

While launchpad had some great ideas, I think they pretty much failed by now and I see much more activity on github, so it might be worthwhile to shut down the launchpad uberwriter "fork" and move everything here and to other services (such as Poeditor).

**Comment by somas95** [comment]
@wolfv you are now an administrator of the project in Poeditor. I already added all the required languages, but as the owner of this repo, only you can link it to the project. 
For doing that just enter [here](https://poeditor.com/github/connect) after reading the confirmation email from poeditor 
A request to change the project from a freemium to a free opens source one has already been sent from me

**Comment by wolfv** [comment]
Hey, I just connected the github to POEditor but I'm not sure it worked for
the uberwriter project.

In the project settings it says I should contact you ;)

Can you check if you have more options now? Or should I open the project
once more and make you an admin?

2018-04-19 15:26 GMT+02:00 somas95 <notifications@github.com>:

**Comment by somas95** [comment]
Hmm... I don't see anything linked
It allows me to connect to my github account and then link each language to the .po file, but only for my owned repos. Don't you see that?
