### ISSUE TITLE
Missing dependency in README

### ISSUE THREAD

**Issue by machinekoder** [UberWriter/uberwriter#54]
### ENVIROMENT
- Linux distribution: Debian Stretch
- Desktop Enviroment: KDE
- DE version:
- GTK version:

### BUG
I needed to install following additional package: `gir1.2-webkit2-4.0` to get it running.

**Comment by somas95** [comment]
Curious, theoretically GTK+ provides webkit2... But other distros, other rules I suppose. I'll put it into the README. Thanks!

**Comment by somas95** [comment]
solved: cb25c85c5d35ca6b52ebf65e2aef2e2b060561db
