### ISSUE TITLE
Consider using Liberapay

### ISSUE THREAD

**Issue by rugk** [UberWriter/uberwriter#56]
I see you are already collecting donations though some platforms for this project.

Maybe you can consider using [Liberapay](https://liberapay.com/) to collect donations?
It is clearly a better alternative for free software than PayPal or so, and it is not just a one-time donation.

**Comment by somas95** [comment]
Done :)
The direction is https://liberapay.com/UberWriter/donate, it will be soon reflected on Flathub et all
