### ISSUE TITLE
Starts with spell checking enabled

### ISSUE THREAD

**Issue by rugk** [UberWriter/uberwriter#57]
The checkbox is disabled at startup, but spell checking is enabled:

![](https://hostux.pics/images/2018/06/11/944e1883dfce13df2963b166d4aea192.png)

Flatpak version, Fedora 28

migrated from https://bugs.launchpad.net/uberwriter/+bug/1776285

**Comment by somas95** [comment]
Fixed - c672091b2230f3ff17fa915861bc31e1c50bc1ce
