### ISSUE TITLE
Menu stays in foreground when window is switched with Wayland

### ISSUE THREAD

**Issue by rugk** [UberWriter/uberwriter#58]
![](https://hostux.pics/images/2018/06/11/9d7b1445e2e765b18003920002c06ff8.png)

BTW, I can actually click on the menu items anyway (although they are shown as if they were disabled) and they work (e.g. the fullscreen option I hover on works.).

Flatpak, Fedora 28

migrated from https://bugs.launchpad.net/uberwriter/+bug/1776286

**Comment by somas95** [comment]
Do you have steps to repoduce it? I can't switch between applications on arch if a menu is active. Also, I don't get the disabled menus. Do you installed it from Flathub or from a custom flatpak compilation?

**Comment by rugk** [comment]
Hu, you can't?

Just:
1. Open application.
2. Open menu.
3. Click on some other application in background or use any other way to switch the application (or s Ctrl+Tab or any other way…)

![switch](https://user-images.githubusercontent.com/11966684/41315715-9e5d0930-6e90-11e8-98dc-3d8436bc44fb.gif)

**Comment by somas95** [comment]
Ding ding ding.
Are you using wayland, no? This only happens in wayland
I set up a VM with fedora and it was exactly as you described. Seems that wayland handles the focus different to xorg. This occurs also with the contextual menu.
For the menus of the headerbar I'll change the widgets that displays them. I think that that will solve the issue, as the pop up widgets are rendered inside the parent window, no over it
For the contextual menu... I suppose that we'll need to destroy it when the focus is lost.
There's something that bothers me. The items are not disabled, *there are in the background*. I mean, when you click on the button, the whole window changes his state. But I couldn't replicate that, even on the fedora VM

**Comment by somas95** [comment]
This will be a lot of fun. We need to change from GtkMenu to GMenuModel (we should do that anyway), and I think that we will need also to change from signals to GActions, as we did with the AppMenu. I'll do that refactoring task after the finals session, as it's quite a bit of work

**Comment by somas95** [comment]
Solved by changing the menu to a popover menu - 80635ac4c063391ca832ea03b1ac4e99c4eca927
I'll do the same for the left menu later, but the bug only affected the right menu.
Also, I think that maybe #60 is solved, but the framerate on the VM I set up was too low to confirm. Could you test it, please? Flatpak doesn't allow nightly builds, but you could clone the repo and just run `./bin/uberwriter`. Maybe you need to copy the gschemas as it's said in the readme

**Comment by rugk** [comment]
I'll just wait for the next release…

**Comment by somas95** [comment]
I understand :)
I updated the translations and pushed the new version to flathub, it will be available soon
