### ISSUE TITLE
Side-by-side preview

### ISSUE THREAD

**Issue by rugk** [UberWriter/uberwriter#59]
It would be great to have a life preview side-by-side (and with scroll sync, i.e. https://bugs.launchpad.net/uberwriter/+bug/1776287) instead of a switch between

This is especially helpful for formulas or so, where you have to verify you actually wrote them correctly.

migrated from https://bugs.launchpad.net/uberwriter/+bug/1776289

**Comment by somas95** [comment]
It is planned, btw you can control-click on a formula to preview it inmediatly without needing to change to preview mode. It also works with images, footnotes, etc

**Comment by rugk** [comment]
Ah, okay, this feature is not really obvious and either needs some explanation or well… when this is implemented it may be obsolete.
