### ISSUE TITLE
 Secondary screen flickers when exiting fullscreen under Wayland

### ISSUE THREAD

**Issue by rugk** [UberWriter/uberwriter#60]
STR:
0. Have a multiscreen setup with one secondary screen.
1. Full screen on primary screen.
(Look at your secondary screen…)
2. Exit (via F11 e.g.)

What happens:
For a short amount of time, the window seems to be shown (maximized or even zoomed in or so) on the secondary screen before the resize animation for exiting the fullscreen ends.

What should happen: obvious

BTW, the animation on the primary screen works as it is supposed to do. It animates nicely and exits full screen.

GNOME, Fedora 28, Flatpak

migrated from https://bugs.launchpad.net/uberwriter/+bug/1776290

**Comment by somas95** [comment]
Couldn't reproduce in Arch, maybe @wolfv can
How frequently happens?
Does it happen also for other applications?

**Comment by rugk** [comment]
It always happens with this one and no it does not happen with any other application.

**Comment by somas95** [comment]
I could replicate the issue in a VM. Let's hope that solving #62 solves this as well, because it seems tricky to debug

**Comment by somas95** [comment]
Well, seems that this only happens in Wayland. So, as a workaround you could change to xorg in the meantime. That also will solve some of the other issues.

**Comment by somas95** [comment]
Seems that this only happens with the Flatpak build. I'll investigate the issue, maybe it's related to the sandboxing doubled sandboxing that wayland and the flatpak specification provide

**Comment by somas95** [comment]
Well, it seems that for some reason the screen object is a GdkX11Screen even on Wayland. I still don't know why, but having a GdkWaylandScreen *could* solve the issue

**Comment by somas95** [comment]
Well, we are not compiling it for flathub with the Wayland socket enabled. I'll address that issue soon

**Comment by somas95** [comment]
It's solved now
