### ISSUE TITLE
Long startup time

### ISSUE THREAD

**Issue by rugk** [UberWriter/uberwriter#65]
For a simple text writer and native application (i..e no Electron) it takes quite much time to start up, typically 3-5 seconds, so it is definitively noticeable.

**Comment by somas95** [comment]
Yes, I know. It's an issue with flatpak: if you run the binary directly it starts in less than 2 secs
Also, this is Python -so it's slower for some things- and some optimizations could be done.
I'll look into it

**Comment by somas95** [comment]
https://github.com/flatpak/flatpak/issues/1768
