### ISSUE TITLE
Sentence is only highlighted if sentence is changed

### ISSUE THREAD

**Issue by mptrsen** [UberWriter/uberwriter#67]
### ENVIROMENT

- Linux distribution: Mint 18
- Desktop Enviroment: XFCE4
- DE version: 4.12.2
- GTK version: 2.24.23

### BUG

The sentence highlighting (which I really like!) is only updated if I change the sentence or start a new one. I would expect it to highlight the sentence the cursor is currently in, regardless of whether it was modified.

**Comment by somas95** [comment]
Fixed by b39b89a261602436d0180b11e12349cf7d54d00a
