### ISSUE TITLE
Redesign of menus

### ISSUE THREAD

**Issue by somas95** [UberWriter/uberwriter#68]
A bit of background. Gnome developers said that AppMenus will be deprecated as soon as Gnome 3.32, and Gnome 3.30 (next release) will be a transition release. AppMenus are the menus that live on the top bar:

![image](https://user-images.githubusercontent.com/8913975/41821287-85f0d88e-77de-11e8-88c2-cd9bec17f9bc.png)

So the contents of that menu will need to be relocated on the window menus, and in the process a little of optimization could be done. Some options could live on the headerbar (save, search). Some could be regrouped in a new dialog (all the different export options) or in a row inside the menu (focus mode - fullscreen - preview). Some mockups:

![image](https://user-images.githubusercontent.com/8913975/41821674-9d2e1966-77e4-11e8-9e77-1ad76e54b4a0.png)

Of course, the icons on the right menu should be ones that reflect their meaning (focus mode - preview - fullscreen)

The open menu would open a popover like the one Gedit has, with a list of recent edited documents, and a button to select other ones. 

This is a open discussion, and I post it here so anyone can suggest their thoughts.

**Comment by wolfv** [comment]
ah, great, finally the quite useless appmenu is going away :)

I really like your mockup! Not sure if doubling the buttons in the settings menu is necessary .. but why not. 
Could also write the text out and make it toggle switches (if that's easier since we don't have any icons yet).

**Comment by somas95** [comment]
That's the current implementation:
![image](https://user-images.githubusercontent.com/8913975/41857602-34272340-7898-11e8-9a5f-0fe2bd5c5335.png)
With the search button on the headerbar I see two alternatives:

1. Move the theme and the spellchecking checkboxes to a preferences window, accesible via the left menu, and getting rid of the right menu completely (the focus mode - preview - fullscreen would be accesible via the bottom bar). This unclutters the headerbar, and unifies all the options in a single menu, so the user doesn't need to think where is x option. Also, these options would be 1-click accesible, which is convenient.

2. Remove the mode - preview - fullscreen buttons from the bottom bar as they're on the right menu. The left menu would be to file related actions and the right one to view and editing related actions. This unclutters the editing area, so it would be less distracting. Also, they don't provide actual useful information (it's obvious if one of the three modes is active) and when the fullscreen headerbar it's ready they won't be necessary for exiting the fullscreen mode for example. One drawback is that they would be two-click away from the user. That's not a problem for fullscreen (F11 is widely known) nor the focus mode (one usually sets the focus mode only once), but is less convenient for the preview option

**Comment by somas95** [comment]
Done in #70
