### ISSUE TITLE
Non-symbolic icons in search bar

### ISSUE THREAD

**Issue by bertob** [UberWriter/uberwriter#71]
### ENVIROMENT
- Linux distribution: PureOS
- Desktop Enviroment: GNOME
- DE version: 3.28
- GTK version: 3.22

### BUG

There are non-symbolic icons in the search bar, which looks a bit out of place. The GNOME HIG recommends always using symbolic icons on buttons (https://developer.gnome.org/hig/stable/icons-and-artwork.html.en).

![image](https://user-images.githubusercontent.com/1908896/43292821-82a4e1b2-9137-11e8-8b57-462541ca5245.png)

**Comment by somas95** [comment]
Good catch!
b09fbba870d498aa8f41eea4e3053554f3e3ebef fixes this. I'll solve some minor bugs before submiting this to flathub
