### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by bertob** [UberWriter/uberwriter#73]
We're working on a new icon style for GNOME, which will make it much easier to make app icons because it's simpler, more geometric, and there are fewer sizes. We will update all core GNOME apps' icons to the new style for 3.32 early next year, but some third-party apps are already starting to use them.

If you're interested in a new icon following the new guidelines I'd be happy to provide one.

**Comment by somas95** [comment]
Sure! Give it to us and we'll see what we can do

**Comment by wolfv** [comment]
That's exciting! :)

**Comment by wolfv** [comment]
Hi @bertob 

thanks so much for your effort! It's really an honour. I think it looks cool.

We were wondering if we could try a bit more minimal version? Maybe one that resembles more a single key on a keyboard? Then we have something to compare.

Cheers,
Wolf

**Comment by bertob** [comment]
@wolfv How about something like this? I tried a single key but it didn't really work. I could still try to simplify this more.

![image](https://user-images.githubusercontent.com/1908896/45370956-a1b80800-b5e9-11e8-9cd2-81ec532bf604.png)

**Comment by somas95** [comment]
I like it :)
I want to ask, were are the new design guidelines? It's soo cool to have a renewed icon set :)
Also, sorry for the lack of input all this time, I've been really busy

**Comment by bertob** [comment]
The new guidelines are still being finalized, but there's already a live version here:

https://developer.gnome.org/hig/stable/icon-design.html.en

**Comment by somas95** [comment]
Hi, @bertob, could you share the svg file? I'd like to test different colour schemes

**Comment by bertob** [comment]
Here's the SVG. If you want to try different colors, have a look at the HIG color palette: https://developer.gnome.org/hig/stable/icon-design.html.en

There's also a .gpl palette here: https://gitlab.gnome.org/Teams/Design/HIG-app-icons/raw/62cb512ff95b2b3d57aeb5f806726d6be2eca74a/HIG.gpl

[zipped icon svg (gitlab doesn't support uploading svg directly)](https://github.com/UberWriter/uberwriter/files/2495644/de.wolfvollprecht.UberWriter.zip)

**Comment by somas95** [comment]
Yeah, I wanted to try different combinations within the official scheme.
Thank you!


En 19 oct. 2018 a 13:42, <Tobias Bernard <notifications@github.com>>
escribió:

Here's the SVG. If you want to try different colors, have a look at the HIG
color palette: https://developer.gnome.org/hig/stable/icon-design.html.en

There's also a .gpl palette here:
https://gitlab.gnome.org/Teams/Design/HIG-app-icons/raw/62cb512ff95b2b3d57aeb5f806726d6be2eca74a/HIG.gpl

zipped icon svg (gitlab doesn't support uploading svg directly)
<https://github.com/UberWriter/uberwriter/files/2495644/de.wolfvollprecht.UberWriter.zip>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/UberWriter/uberwriter/issues/73#issuecomment-431335561>,
or mute the thread

**Comment by somas95** [comment]
A really quick test to try different color combinations and ideas
Personally I like more the logo being less color-saturated (and I see you tried a monochrome version of the original typewriter, @bertob), but with a touch of color
What do you think, @wolfv , @bertob?
I put a "neutral" background to better appreciate the lighter icons, but we should acknowledge that GNOME will draw drop-shadows in light icons when they are in front off light backgrounds
![g1673](https://user-images.githubusercontent.com/8913975/47231158-7684bd80-d3cc-11e8-8377-50279cdbd09d.png)

**Comment by bertob** [comment]
I don't think the orange text makes sense, but i like the one orange key idea.

Taking it a bit further, maybe we could have multiple keys with different colors like on one of those old school mechanical keyboards?

![image](https://user-images.githubusercontent.com/1908896/47235804-6ecc1580-d3da-11e8-8602-f1e46f17295d.png)

**Comment by westscz** [comment]
I like this orange key idea too :+1: 
If we think about typewriter icon, this first idea was for me better than orange text. Maybe only orange key will be look better there

**Comment by somas95** [comment]
While I like the lighter spacebar, I think that it makes the 32x32 icon more confusing, and as far as I know the new guidelines states that an unique svg icon should be used for all the resolutions, right, @bertob?

**Comment by bertob** [comment]
@somas95 Using the hicolor app icons at <64px is not recommended, the size is included in Icon Preview for testing purposes only (maybe we should make that clearer in the UI).

**Comment by somas95** [comment]
Hi, @bertob, it would be nice to do the next release with the new icon. Do you think it's finished? Could we use it?
Cheers, and thanks for your incredible job :)

**Comment by bertob** [comment]
@somas95 I'm quite happy with it now, so works for me :)

Here's a zip with the icon (Gtihub doesn't allow SVG):

[de.wolfvollprecht.UberWriter.zip](https://github.com/UberWriter/uberwriter/files/2612612/de.wolfvollprecht.UberWriter.zip)
