### ISSUE TITLE
Opening tutorial causes unsaved changes to current document to be lost

### ISSUE THREAD

**Issue by twright** [UberWriter/uberwriter#77]
### ENVIROMENT
- Linux distribution: Fedora 29 (beta)
- Desktop Enviroment: Gnome
- DE version: 3.30
- GTK version: 3.30
 - Uberwriter version: 2.1.2

### BUG

When opening the tutorial, any unsaved changes to the current document will be lost.

#### Steps to reproduce:

1. Open UberWriter
2. Start typing
3. Select menu item `Open Tutorial'

#### Observed behaviour:
Tutorial is opened in editor with no apparent way to return to original (unsaved) document.

#### Expected behaviour:
Tutorial should open in a new window, or, at the very least, a chance to save the original document should be offered.

**Comment by somas95** [comment]
I'll look at it this weekend. I've been busy lately, but I'll have more time now to work on this

**Comment by somas95** [comment]
Yes, I just pushed a lot of changes today :)
Now I'm struggling with the translations (they're not shown up on the menu), but whenever that minor detail is fixed I'll push all of this to flathub

**Comment by somas95** [comment]
Oh shit, it was my fault. My locales were wrong. Tomorrow we'll have a new version if everything works ok :)
