### ISSUE TITLE
setup.py installing into wrong folders

### ISSUE THREAD

**Issue by yochananmarqos** [UberWriter/uberwriter#78]
### ENVIROMENT
- Linux distribution: Manjaro Linux
- Desktop Enviroment: Cinnamon
- DE version: 3.8.9
- GTK version: 3.24.1+8+g220f77d8c1-1

### BUG
I tried building from source, but it's installing into` /bin`, `/lib`and `/share` instead of `/usr/bin`, `/usr/lib` and `/usr/share`. 

I tried the following changes in `setup.py`, but it installed into `/usr/usr/` instead.

```
data_files=[
        (app_prefix + 'usr/bin/', ['bin/uberwriter']),
        (app_prefix + 'usr/share/glib-2.0/schemas', ['data/de.wolfvollprecht.UberWriter.gschema.xml']),
        (app_prefix + 'usr/share/icons/hicolor/scalable/apps', ['data/media/uberwriter.svg']),
        (app_prefix + 'usr/share/applications', ['de.wolfvollprecht.UberWriter.desktop']),
        (app_prefix + '/opt/uberwriter/data/ui', extra_files_ui),
        (app_prefix + '/opt/uberwriter/data/media', extra_files_media),
        (app_prefix + '/opt/uberwriter/data/lua', extra_files_scripts)
    ]
```

If I change `app_prefix = ''` to `app_prefix = '/usr'`, then it installs everything into `/usr` including `/opt`.

What's the solution here?

**Comment by somas95** [comment]
I'll look at it this weekend. I know that our setup.py it's a little messy, as we try to provide a system-wide and flatpak copatible installer at the same time. I need to package it to the AUR repo, so that could be your way to install it in a near future, as you use Manjaro

**Comment by somas95** [comment]
Well, I must say that this issue was already fixed, as you can see in https://github.com/UberWriter/uberwriter/blob/refactoring/setup.py. Soon I'll merge the refactoring branch with master, as some important bugfixes are there (it's not easy to have separate development branchs if one of them is for refactoring. Git has it's limitations)

**Comment by yochananmarqos** [comment]
FYI, it's already in the AUR as [`uberwriter`](https://aur.archlinux.org/packages/uberwriter) and [`uberwriter-git`](https://aur.archlinux.org/packages/uberwriter-git). They're both broken and the PKGBUILDs are a mess. I would contact the maintainer.

I built from the refactoring tree and it installs everything in `usr` including opt. This is the PKGBUILD I'm using. I'm not sure about the dependencies other than `gtk3` & `python`.
```
pkgname=uberwriter-refactoring-git
_pkgname=uberwriter
pkgver=2.1.2.r13.g202ac17
pkgrel=1
pkgdesc='A distraction free Markdown editor for GNU/Linux made with GTK+'
arch=('any')
url='http://uberwriter.github.io/uberwriter/'
license=('GPL3')
depends=('gtk3' 'python')
makedepends=('python-setuptools')
provides=("_pkgname")
conflicts=("$_pkgname" "$_pkgname-git")
source=('git+https://github.com/UberWriter/uberwriter.git#branch=refactoring')
sha256sums=('SKIP')

pkgver() {
    cd $_pkgname
    git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

package() {
    cd $_pkgname
    python setup.py install --root="$pkgdir" --optimize=1
}
```

**Comment by somas95** [comment]
I know, I know. In fact I took the maintainership of one of them, but never had the time to prepare a proper PKGBUILD. Some of the most important dependencies are listed in the README, but it should work with
- python
- gtk
- pandoc
- python-gtkspellcheck
Also you should install the font 
- Fira Mono

For exporting, texlive-core is the minimum needed, but some texlive packages are recomended to have proper LaTeX support

I don't know why it installs everything in /usr, try changing
python setup.py install --root="$pkgdir" --optimize=1
to something like
python setup.py install --root="/" --optimize=1

Anyway, setuptools complicated the installation process, maybe more or different arguments are needed.

Last but not last, you'll need to install the gschemas:

`sudo cp data/de.wolfvollprecht.UberWriter.gschema.xml /usr/share/glib-2.0/schemas/de.wolfvollprecht.UberWriter.gschema.xml`

`sudo glib-compile-schemas /usr/share/glib-2.0/schemas`

Let's see if we can get an PKGBUILD up and running

**Comment by somas95** [comment]
>No need to copy the gschema.xml as setup.py already does.

Holy shit, I wrote that code. It's obvious that I was pretty asleep this morning 😅
I'll review all of that. Thanks for the update!

**Comment by somas95** [comment]
@yochananmarqos just FYI, I added your PKGBUILD (4e8d8fa49141241336273f6517c66f5f2c71821d) and fixed the install directory issue (61f3122afc0ad7afc25bfb85178f65e1a86555ed); the patch is no longer needed :)
Thanks for your help with the PKGBUILD! Now I only need to push it to the AUR

**Comment by yochananmarqos** [comment]
Hooray, it works!

Turns out calling `glib-compile-schemas` is not necessary:

> Do not call `glib-compile-schemas` in the .install file, as GSettings schema databases are automatically recompiled via pacman hooks since `glib2`=2.48.0-2

-- [GNOME package guildlines - ArchWiki](https://wiki.archlinux.org/index.php/GNOME_package_guidelines#GSettings_schemas)

FYI, the PKGBUILD you added still has the patch included and the `pkgname` is wrong. Here are three PKGBUILDs: One for the tarball release, one that builds from git:master and one that builds from git:refactoring. Of course, the first two won't install properly yet until the changes in refactoring are merged.
```
pkgname=uberwriter
pkgver=2.1.2
pkgrel=1
pkgdesc='A distraction free Markdown editor for GNU/Linux made with GTK+'
arch=('any')
url='http://uberwriter.github.io/uberwriter'
license=('GPL3')
depends=('gtk3' 'pandoc' 'python-gtkspellcheck')
makedepends=('python-setuptools')
optdepends=('texlive-core' 'otf-fira-mono: Recommended font')
conflicts=("$pkgname-git" "$pkgname-refactoring-git")
source=("$pkgname-$pkgver.tar.gz::https://github.com/UberWriter/uberwriter/archive/v$pkgver.tar.gz")
md5sums=('51830bf961dc1515885b5ed901c1de62')

 build() {
    cd $_pkgname
    python setup.py build
}

 package() {
    cd $_pkgname
    python setup.py install --skip-build --root="$pkgdir" --optimize=1
}
```
----
```
pkgname=uberwriter-git
_pkgname=uberwriter
pkgver=2.1.2.r0.g2b25681
pkgrel=1
pkgdesc='A distraction free Markdown editor for GNU/Linux made with GTK+'
arch=('any')
url='http://uberwriter.github.io/uberwriter'
license=('GPL3')
depends=('gtk3' 'pandoc' 'python-gtkspellcheck')
makedepends=('python-setuptools')
optdepends=('texlive-core' 'otf-fira-mono: Recommended font')
provides=("$_pkgname")
conflicts=("$_pkgname" "$_pkgname-refactoring-git")
source=('git+https://github.com/UberWriter/uberwriter.git')
sha256sums=('SKIP')

pkgver() {
    cd $_pkgname
    git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
    cd $_pkgname
    python setup.py build
}

package() {
    cd $_pkgname
    python setup.py install --skip-build --root="$pkgdir" --optimize=1
}
```
----
```
pkgname=uberwriter-refactoring-git
_pkgname=uberwriter
pkgver=2.1.2.r20.gca75862
pkgrel=1
pkgdesc='A distraction free Markdown editor for GNU/Linux made with GTK+'
arch=('any')
url='http://uberwriter.github.io/uberwriter/'
license=('GPL3')
depends=('gtk3' 'pandoc' 'python-gtkspellcheck')
makedepends=('python-setuptools')
optdepends=('texlive-core' 'otf-fira-mono: Recommended font')
provides=("$_pkgname")
conflicts=("$_pkgname" "$_pkgname-git")
source=('git+https://github.com/UberWriter/uberwriter.git#branch=refactoring')
sha256sums=('SKIP')

pkgver() {
    cd $_pkgname
    git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
    cd $_pkgname
    python setup.py build
}

package() {
    cd $_pkgname
    python setup.py install --skip-build --root="$pkgdir" --optimize=1
}
```

**Comment by somas95** [comment]
My fault, I forgot to push the removal of the patch, but I have it fixed in local.
Good to see that pacman compiles the schemas automagically (each day I love that package manger more), sadly Flatpak doesn't do that, so I'll have to do a little tweaking
One more time, thanks for your help! :)
