### ISSUE TITLE
Git Commits

### ISSUE THREAD

**Issue by tronta** [UberWriter/uberwriter#80]
What I would find pretty cool if it could have a git integration.
So if uberwriter detects that the file is part of a git repository the save button is replaced by a small text input field. When storing a change one enters a message in the text field and presses enter (instead of pressing the save button).
Then the file is automatically committed with the entered message.

What do you think?

**Comment by somas95** [comment]
I don't see it, and for a couple of reasons:
- Saving and committing are two very unrelated things in general
- We would miss a lot of use cases: branches, pulling, pushing, etc
At the end of the day you want to use the terminal or a gui git manager like gitg
