### ISSUE TITLE
UberWriter Does Not Use Dark GTK Theme On Startup With Dark Theme Preference

### ISSUE THREAD

**Issue by BrainBlasted** [UberWriter/uberwriter#81]
### ENVIROMENT
- Linux distribution: Arch Linux
- Desktop Enviroment: GNOME
- DE version: 3.30.2
- GTK version: 3.24

### BUG
When setting the "Use dark mode" preference in UberWriter, if you restart the app UberWriter does not set the GTK3 theme as the dark theme. This is done with the GtkSetting `gtk-application-prefer-dark-theme`.

**Comment by somas95** [comment]
Fixed by cbd59b5f0ba28240936742343f9181b5958a33df
