### ISSUE TITLE
[Feature Request] More format highlighting

### ISSUE THREAD

**Issue by nsrosenqvist** [UberWriter/uberwriter#90]
Currently neither links or code blocks are highlighted in the editor. Block quotations would also be nice to have some different styling to, as well as footnotes and title blocks.

**Comment by nsrosenqvist** [comment]
Related: #14

**Comment by somas95** [comment]
Thi is something rather easy to do, I think I'll upper it in my to-do list. Also, thanks for suggesting all these features :)

**Comment by nsrosenqvist** [comment]
I've used UberWriter as my go to editor for a couple of years now, thank you so much for picking up the development of it again!

**Comment by somas95** [comment]
Btw, you know that you can ctrl+click on a footnote to preview it? 






On Fri, Nov 23, 2018 at 6:05 AM +0100, "Niklas Rosenqvist" <notifications@github.com> wrote:












Currently neither links or code blocks are highlighted in the editor. Block quotations would also be nice to have some different styling to, as well as footnotes and title blocks.

**Comment by fbruetting** [comment]
I’d also like to see a more colorful (and ideally customizable) highlighting of Markdown “code” parts. For example bullets, checkboxes, brackets which are parsed by markdown ( `[links](like that)` or colors for a certain subset of upper-level headings (a fine-tunable size for each heading would be rad, btw.). Here is one example which shows UberWriter compared to Ghostwriter:

![Bildschirmfoto von 2019-04-02 15-58-11](https://user-images.githubusercontent.com/10520767/55408578-96660300-5560-11e9-9d85-ceb2f9430714.png)

![Bildschirmfoto von 2019-04-02 15-58-26](https://user-images.githubusercontent.com/10520767/55408581-9960f380-5560-11e9-8b64-fff421c1a020.png)
