### ISSUE TITLE
Missing Italian Language on POEditor

### ISSUE THREAD

**Issue by thegoldgoat** [UberWriter/uberwriter#97]
I am not sure if I can add it in some way, but I can't find any option for an Italian Localization on <https://poeditor.com/join/project/gxVzFyXb2x>

**Comment by somas95** [comment]
Give me some hours and I'll create it :)
Thanks for joining the localization team!

**Comment by thegoldgoat** [comment]
Great!
Waiting for it :)


Il giorno lun 10 dic 2018, 17:02 somas95 <notifications@github.com> ha
scritto:

**Comment by somas95** [comment]
There it goes :)
<https://poeditor.com/projects/po_edit?id=178989&id_language=75>
Join from the link you posted, I'll aprove you tomorrow as soon as I can

**Comment by somas95** [comment]
There you go! What do you prefer for the "About" credits, your name or your nick, @thegoldgoat?

**Comment by thegoldgoat** [comment]
Full name "Andrea Somaini" please
Thanks! I'll work on that as soon as I can

**Comment by somas95** [comment]
Thanks to you :)

**Comment by somas95** [comment]
@thegoldgoat you....you just translated the entire app! In two days! It's incredible. Many many thanks ^^
If you have a request, anything you would like in the app, tell me. I can't guarantee anything, but I'll up it in my to-do list if it's in my hand

**Comment by thegoldgoat** [comment]
Thanks! I think this is a great app, and I don't have any particular request :)
This was my first translation, so I am not sure everything is completely right, and I don't know how to test it

**Comment by somas95** [comment]
It's not trivial to do, even if you install from git, as Poeditor doesn't allow you to export the .po files
I could sare with you screenshots of the application with the italian language loaded, or I can export the po and mo files so you can try them with a cloned copy of this repo. Or you can wait to the next release, which will ship your translations :)

**Comment by thegoldgoat** [comment]
Actually I can download the .po file, I have placed it in the it directory and compiled it with complile_translation.sh, but I don't know how to run the app in italian

**Comment by somas95** [comment]
First be sure that it is in the po/it/LC_MESSAGES there is a file called uberwriter.mo and it's not empty.
Uberwriter will detect your system language. Be aware that some terminal emulators don't set the lang env variables correctly (like VSCode). You can always run something like `exportLANG=it`  berfore running the program

**Comment by thegoldgoat** [comment]
It was VSCode as you mentioned. Thanks, now it is translated
But I guess `export LANG=it` is not enough from VSCode: as you can see below, some elements are not translated.
![image](https://user-images.githubusercontent.com/25644731/50231201-8873e400-03ae-11e9-9fd2-2425b354f8ea.png)
If I run it from gnome-terminal and it works fine, thanks :)
I checked my translation, they are right.

**Comment by somas95** [comment]
Haha, it took me a while to find out that VSCode messes the locales :)
