### ISSUE TITLE
Too much whitespace on "unsaved changes" dialog

### ISSUE THREAD

**Issue by bertob** [UberWriter/uberwriter#98]
### ENVIROMENT
- Linux distribution: PureOS
- Desktop Enviroment: GNOME
- DE version: 3.30
- GTK version: 3.24

### BUG

The error dialog I get when trying to close the window with unsaved changes has a lot of unnecessary whitespace below the description.

![screenshot from 2018-12-12 21-25-37](https://user-images.githubusercontent.com/1908896/49896761-a3959f80-fe54-11e8-8238-d37de9eac30b.png)

**Comment by somas95** [comment]
7066f446d2f3de41af68f9a0f3b0c49bd65b8b3e
