### ISSUE TITLE
Join open button and file history button visually

### ISSUE THREAD

**Issue by bertob** [UberWriter/uberwriter#99]
### ENVIROMENT
- Linux distribution: PureOS
- Desktop Enviroment: GNOME
- DE version: 3.30
- GTK version: 3.24

### BUG

The down-arrow button for the file history is disconnected from the open button, which is a bit weird.

![image](https://user-images.githubusercontent.com/1908896/49897233-d8562680-fe55-11e8-8d7f-116f21d433d1.png)

It would make more sense and be more consistent with what other apps do if the buttons were joined as a segmented button, like so:

![image](https://user-images.githubusercontent.com/1908896/49897529-bad58c80-fe56-11e8-8a1b-576c98cd8a04.png)

I'd also suggest changing the icon to pan-down-symbolic, since that's what other apps use for this kind of menu.

**Comment by bertob** [comment]
I think it's fine to keep labels for the buttons here. I'm just suggesting joining the open button with the arrow button, like so:

![image](https://user-images.githubusercontent.com/1908896/50020695-19c20f80-ffd7-11e8-9f5e-1f84f7501fc1.png)

**Comment by somas95** [comment]
Just did it 3fd91923ee75008d52fa24da149f6e0bdf987db6
Keeping the labels, I like them more, they are more clean and clear
